#!/bin/sh
cat readme >  README.md
cat installations >> README.md
git init
git add .
git commit -m "first commit"
git remote add origin https://github.com/Alex-Tsvetanov/Triangulation.git
git push -u origin master
